### ISSUE TITLE
Support for configuration snippets embeddable into scripts

### ISSUE THREAD

**Issue by dnet** [silentsignal/burp-piper#8]
When sharing useful scripts that can be used by Piper, it might help installing such a script if the YAML configuration could be embedded in a multiline comment or string. This way, the script itself would ignore it, but Piper could "install" the script by parsing the embedded YAML metadata.

An imaginary example:

```yaml
-----BEGIN PIPER METADATA-----
Type: messageViewer
Placeholder: SCRIPTNAME

prefix: [python, SCRIPTNAME]
inputMethod: stdin
name: Widget frobnicator
filter:
  regex:
    pattern: ^widget
-----END PIPER METADATA-----
```
